<?php

/**
 * @file
 * Primary module hooks for cp_chat module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

function cp_layout_theme($existing, $type, $theme, $path)
{
  $uid = \Drupal::currentUser();
  $user = \Drupal\user\Entity\User::load($uid->id());
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  //force language in all paths
  $variables['language'] = $language == 'en' ? 'EN' : 'ES';
  $variables['language_2'] = $language != 'en' ? 'EN' : 'ES';

  if($user->isActive()){

    //check if has exporter rol
    // chek if user is not root
    if($user->hasRole('exportador')){
      //is not empty field_company_name
      if(!empty($user->get('field_company_name')->value)){
        $variables['business_name'] = $user->get('field_company_name')->value;
        $variables['company_logo'] = file_create_url($user->get('field_company_logo')->entity->getFileUri());
      }
      else{
        $variables['company_logo'] = '';
        $variables['business_name'] = '';
      }
    }
  }
  //is not empty field_company_name
  $variables['name'] = $user->get('field_company_contact_name')->value;
  $variables['lastname'] = $user->get('field_company_contact_lastname')->value;
  //get email
  $variables['email'] = $user->get('mail')->value;
  return [
    // Name of the theme hook. This is used in the controller to trigger the hook.
    'cp_message_sidebar_template_hook' => [
      'render element' => 'children',
      // If no template name is defined here,
      // it defaults to the name of the theme hook,
      // ie. module-name-theme-hook.html.twig
      'template' => 'cp_message_sidebar_template',
      // Optionally define path to Twig template files.
      // Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
    ],
    'cp_header_not_sign_in_template_hook' => [
      'render element' => 'children',
      // If no template name is defined here,
      // it defaults to the name of the theme hook,
      // ie. module-name-theme-hook.html.twig
      'template' => 'cp_header_not_sign_in_template',
      'variables' => [
        'language' => $variables['language'],
        'language_2'=> $variables['language_2']
      ],
      // Optionally define path to Twig template files.
      // Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
    ],
    'cp_header_exportador_template_hook' => [
      'render element' => 'children',
      // If no template name is defined here,
      // it defaults to the name of the theme hook,
      // ie. module-name-theme-hook.html.twig
      'template' => 'cp_header_exportador_template',
      'variables' => [
        'language' => $variables['language'],
        'language_2'=> $variables['language_2'],
        'business_name' => $variables['business_name'],
        'company_logo' => $variables['company_logo']
      ],
      // Optionally define path to Twig template files.
      // Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
    ],
    'cp_header_buyer_template_hook' => [
      'render element' => 'children',
      // If no template name is defined here,
      // it defaults to the name of the theme hook,
      // ie. module-name-theme-hook.html.twig
      'template' => 'cp_header_buyer_template',
      'variables' => [
        'language' => $variables['language'],
        'language_2'=> $variables['language_2'],
        'name' => $variables['name'],
        'lastname' => $variables['lastname'],
        'email' => $variables['email']
      ],
      // Optionally define path to Twig template files.
      // Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
    ],
    'cp_header_advisor_col_template_hook' => [
      'render element' => 'children',
      // If no template name is defined here,
      // it defaults to the name of the theme hook,
      // ie. module-name-theme-hook.html.twig
      'template' => 'cp_header_advisor_col_template',
      'variables' => [
        'language' => $variables['language'],
        'language_2'=> $variables['language_2'],
        'name' => $variables['name'],
        'lastname' => $variables['lastname'],
        'email' => $variables['email']
      ],
      // Optionally define path to Twig template files.
      // Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
    ],
    'cp_header_advisor_international_template_hook' => [
      'render element' => 'children',
      // If no template name is defined here,
      // it defaults to the name of the theme hook,
      // ie. module-name-theme-hook.html.twig
      'template' => 'cp_header_advisor_international_template',
      'variables' => [
        'language' => $variables['language'],
        'language_2'=> $variables['language_2'],
        'name' => $variables['name'],
        'lastname' => $variables['lastname'],
        'email' => $variables['email']
      ],
      // Optionally define path to Twig template files.
      // Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
    ],
  ];
}