<?php

/**
 * Implements hook_theme().
 *
 * Register a module or theme's theme implementations.
 * The implementations declared by this hook specify how a 
 * particular render array is to be rendered as HTML.
 *
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme/8.2.x
 *
 * If you change this method, clear theme registry and routing 
 * table 'drush cc theme-registry' and 'drush cc router'.
 */
function cp_pro_adviser_theme($existing, $type, $theme, $path)
{

  return [
    // Name of the theme hook. This is used in the controller to trigger the hook.
    'cp_dashboard_pro_adviser_template_hook' => [
      'render element' => 'children',
      // If no template name is defined here,
      // it defaults to the name of the theme hook,
      // ie. module-name-theme-hook.html.twig
      'template' => 'cp_dashboard_pro_adviser_template',
      'variables' => [
        'data' => null,
        'tree_production_chain'=> null,
        'tree_business_model'=> null,
        'tree_categorization'=> null,
        'tree_deparment'=> null,
        'tree_account_status'=> null,
        'tree_users'=> null,
      ],
      // Optionally define path to Twig template files.
      // Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
    ],
    'cp_dashboard_pro_adviser_international_template_hook' => [
      'render element' => 'children',
      // If no template name is defined here,
      // it defaults to the name of the theme hook,
      // ie. module-name-theme-hook.html.twig
      'template' => 'cp_dashboard_pro_adviser_international_template',
      'variables' => [
        'data' => null,
        'tree_production_chain'=> null,
        'tree_business_model'=> null,
        'tree_categorization'=> null,
        'tree_deparment'=> null,
        'tree_account_status' => null,
      ],
      // Optionally define path to Twig template files.
      // Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
    ],
    'cp_review_pro_adviser_template_hook' => [
      'render element' => 'children',
      // If no template name is defined here,
      // it defaults to the name of the theme hook,
      // ie. module-name-theme-hook.html.twig
      'template' => 'cp_review_pro_adviser_template',
      'variables' => [
        'tree_categorization' => null,
        'tree_business_model' => null,
        'tree_account_status' => null,
      ],
      // Optionally define path to Twig template files.
      // Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
    ],
    'cp_edit_col_company_template_hook' => [
      'render element' => 'children',
      // If no template name is defined here,
      // it defaults to the name of the theme hook,
      // ie. module-name-theme-hook.html.twig
      'template' => 'cp_edit_col_company_template',
      'variables' => [
        'deparments' => null,
        'production_chain' => null,
        'business_model' => null,
        'certificacion_de_empresa' => null,
        'countries' => null,
      ],
      // Optionally define path to Twig template files.
      // Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
    ],
    'cp_edit_international_company_template_hook' => [
      'render element' => 'children',
      // If no template name is defined here,
      // it defaults to the name of the theme hook,
      // ie. module-name-theme-hook.html.twig
      'template' => 'cp_edit_international_company_template',
      'variables' => [
        'tree_categorization' => null,
        'tree_business_model' => null,
        'tree_countries' => null,
        'tree_advisor' => null,
      ],
      // Optionally define path to Twig template files.
      // Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
    ],
  ];
}