<?php
/**
 * Implement hook_theme().
 */
function cp_search_theme($existing, $type, $theme, $path) {
  return array(
    'cpSearch' => array(
      'variables' => array(
        'html_view'   => NULL,
        'link_erase_all' => NULL,
        'li_exp_mark' => NULL,
        'li_cert' => NULL,
        'num_elems' => NULL,
        'name_cat' => NULL,
        'name_cat_description' => NULL,
        'name_subcat' => NULL,
        'filters_selected' => NULL,
        'dante' => NULL,
        'ecom' => NULL,
        'title_h1' => NULL,
      ),
      'template' => 'search'
    ),
    'filtersSearch' => array(
      'variables' => array(
        'form'   => NULL,
      ),
      'template' => 'filters'
    ),
    'catgsHierarchy' => array(
      'variables' => array(
        'parent'   => NULL,
        'child'   => NULL,
      ),
      'template' => 'catsHierarchyy'
    ),
    'bannerCategory' => array(
      'variables' => array(
        'uri_img'   => NULL,
        'taxonomy_name'   => '',
      ),
      'template' => 'bannerCategory',
      'cache'=> false
    ),
    'swLanguage' => array(
      'variables' => array(
        'urls'   => NULL,
        'currentLang' => NULL,
      ),
      'template' => 'swLanguage'
    ),
  );
}
