<?php

/**
 * @file
 * CP Field features module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function cp_field_features_theme() {
  return [
    'cp_field_features_multiple_value_form' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_preprocess_hook().
 */
function template_preprocess_cp_field_features_multiple_value_form(&$variables) {
  $variables['elements'] = [];
  $element = $variables['element'];
  foreach (Element::children($element) as $key) {
    $variables['elements'][] = $element[$key];
  }
}
